#!/usr/bin/env python
import argparse
import sys
import re
import os
import stat

from bson import Binary, Code
from bson.json_util import dumps

from json import loads as jsonLoads
from json import dumps as jsonDumps

if __name__ == '__main__':
    PARSER = argparse.ArgumentParser(description='''
        get an arry from a field exists in a list of json documents
   ''',
   formatter_class=argparse.ArgumentDefaultsHelpFormatter)

    PARSER.add_argument('-f', '--fieldName', default="_id", help='field name in json')
    PARSER.add_argument('-s', '--seperator', default=", " , help='specify field seperator')
    PARSER.add_argument('-l', '--leftBorder', default='[', help='left border')
    PARSER.add_argument('-r', '--rightBorder', default=']', help='right border')

    args = PARSER.parse_args()

    mode = os.fstat(0).st_mode
    if stat.S_ISFIFO(mode):
        result = []
        for line in sys.stdin:
            currentJson = jsonLoads(line)
            if args.fieldName in currentJson:
                result.append(str(currentJson[args.fieldName]))

        print(args.leftBorder + args.seperator.join(result) + args.rightBorder)

