#!/usr/bin/env python
import argparse
import sys
import re
import os
import datetime
import xlrd

from bson import Binary, Code
from bson.json_util import dumps

from json import loads as jsonLoads
from json import dumps as jsonDumps

if __name__ == '__main__':

    PARSER = argparse.ArgumentParser(description='''
        get excel sheet content
    ''')
    
    PARSER.add_argument('-f', '--filename', help='filename of the excel sheet')
    PARSER.add_argument('-s', '--seperator', default=" - ", help='field seperator')
    
    PARSER.add_argument('-1', '--firstLine', action="store_true", help='show only first line')
    PARSER.add_argument('-t', '--tail', action="store_true", help='only content after fist line')

    args = PARSER.parse_args()

    if not args.filename:
        raise Exception("no excel file given.")

    if not os.path.isfile(args.filename):
        raise Exception("file not found.")
    
    book = xlrd.open_workbook(args.filename)
    sh = book.sheet_by_index(0)
    rows = list(sh.get_rows())

    if args.tail:
        rows = rows[1:]

    for row in rows:
        print (args.seperator.join([ str(x.value) for x in row  ])) 
        if args.firstLine:
            sys.exit(0)
